Lab 1
Dmitry505/Academy_Effective pull request #1
Opened 2024-11-15 16:41 UTC by Dmitry505

Lab 1. Cоздание и подготовка сайта.

2024-11-15 16:43 UTC, Dmitry505 commented
Сделал лабораторную позже т.к. уезжал в другой город. Остальные буду сдавать в срок.
Об этом предупреждал Татьяну Юрьевну.

2024-11-19 19:09 UTC, ayusavin requested changes
Поправь замечания

2024-11-19 19:09 UTC, ayusavin commented on README.md
> +    py manage.py runserver
Нужно дописать README, добавить прогон миграций, а также необходимые инструменты (Python, Poetry)

2024-11-19 19:09 UTC, ayusavin commented on locallibrary/locallibrary/settings.py
> +SECRET_KEY = 'django-insecure-vp@k$w_v9l34mui**d_erqlyywxgble$fmh$hf)4ct05s7=*_!'
Вынести в перменные окружения

2024-11-19 19:09 UTC, ayusavin commented on locallibrary/locallibrary/settings.py
> +DEBUG = True
Вынести в перменные окружения

2024-11-19 19:09 UTC, ayusavin commented on pyproject.toml
> +black = "^24.10.0"
Зависимости из раздела `tool.poetry.dependencies` должны содержать исключительно зависимости, которые нужны для запуска приложения, чтобы можно было разделять то, что нужно для сборки приложения и то, что нужно для разработки, поэтому необходимо вынести `black` и `mypy-extensions` в группу `dev` зависимостей Poetry:

```toml
[tool.poetry.dependencies]
python = "^3.12"
asgiref = "^3.8.1"
click = "^8.1.7"
colorama = "^0.4.6"
django = "^5.1.3"
djangorestframework = "^3.15.2"
packaging = "^24.2"
pathspec = "^0.12.1"
platformdirs = "^4.3.6"
python-dotenv = "^1.0.1"
sqlparse = "^0.5.2"
tzdata = "^2024.2"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
mypy-extensions = "^1.0.0"
```

2024-12-02 13:43 UTC, ayusavin approved these changes
@Dmitry505, поправь ошибки в README и сливай в main

2024-12-02 13:43 UTC, ayusavin commented on README.md
> -    py manage.py runserver
Лучше использовать вместо своего алиса общий `python3` а также важно объявлять, что за интерпретатор мы хотим запускать - интерпретатор из контекста poetry, который знает о всех зависимостях:
```bash
# Migrations
poetry run python3 manage.py makemigrations
poetry run python3 manage.py migrate

# Start server
poetry run python3 manage.py runserver
```

2024-12-02 13:43 UTC, ayusavin commented on README.md
> +6. Создание миграций  в бд
Миграции должны идти до запуска сервера

2024-12-03 14:55 UTC, merged