Lab 2
Dmitry505/Academy_Effective pull request #2
Opened 2024-11-19 16:53 UTC by Dmitry505

Lab 2

2024-12-02 13:51 UTC, ayusavin requested changes
@Dmitry505, установи себе расширение для линтера в IDE:

Для PyCharm это https://plugins.jetbrains.com/plugin/11084-pylint
Для VS Code это https://marketplace.cursorapi.com/items?itemName=ms-python.pylint
А также установи pylint либо ruff, как dev зависимость и прогоняй линтер каждый раз перед тем, как заливать изменения в репозиторий. Помогает отлавливать нарушения код-стайла PEP-8.

Поправь обозначенные мной ошибки, а также те, которые сам найдешь и залей изменения.

@Dmitry505, тегни меня в Pull Request, как только будет готово.

2024-12-02 13:51 UTC, ayusavin commented on README.md
См замечания в #1

2024-12-02 13:51 UTC, ayusavin commented on locallibrary/catalog/models.py
> +    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")
Нарушение PEP-8 в большом количестве файлов есть [строки размером > 79 симовлов](https://peps.python.org/pep-0008/#maximum-line-length):
> * Limit all lines to a maximum of 79 characters.

Решается это разными способами:
1. Если это комментарии делай так
```python
# Bad
# Super very huge massive mega uper duper biggest then ever mega big comment

# Good: split on lines
# Super very huge massive mega 
# uper duper biggest then ever mega 
# big comment

# Also good solution: convert to docstring
"""
Super very huge massive mega 
uper duper biggest then ever mega 
big comment
"""
```
2. Для больших строк в коде используй конкатенацию и `expression braces` (более красиво) или multi-line strings
```python
# Not good at all, hard to read
big_string: str = "Super very huge massive mega uper duper biggest then ever mega big string value"

# Good
big_string: str = (
  "Super very huge massive mega uper "
  "duper biggest then ever mega "
  "big string value"
)

# Or with multi-line strings
# Backslash '\' symbol here is using
# to terminate '\n'
big_string: str = """\
Super very huge massive mega uper \
duper biggest then ever mega \
big string value\
"""
```
3. Для кода рекомендуется также использовает `expression braces`
```python
# Not good
big_statement_result = builder.config(...).config(...).config(...).config(...).config(...).config(...).config(...).build()

# Good
big_statement_result = (
  builder
  .config(...)
  .config(...)
  .config(...)
  .config(...)
  .config(...)
  .build()
)
```
Ну а если размер кода растет вширь за счет размера циклов и if-else конструкций, то тут уже нужно упрощать логику в этом коде. См. [цикломатическая сложность](https://en.wikipedia.org/wiki/Cyclomatic_complexity#Interpretation)

2024-12-02 13:51 UTC, ayusavin commented on locallibrary/catalog/models.py
> +    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")
Конкретно здесь поле красиво можно записать, как:
```python
name = models.CharField(
  max_length=200,
  help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
)
```

2024-12-02 13:51 UTC, ayusavin commented on pyproject.toml
> +djangorestframework = "^3.15.2"
djangorestframework можно удалить, он не используется в самих лабораторных

2024-12-02 13:51 UTC, ayusavin commented on locallibrary/catalog/models.py
> +import uuid
Нарушение порядка импортов по PEP-8
```
Imports should be grouped in the following order:

- Standard library imports.
- Related third party imports.
- Local application/library specific imports.
You should put a blank line between each group of imports.
```

Конкретно здесь нужно вынести uuid, который находится в стандартной библиотеке Python, наверх:
```python
import uuid

from django.db import models
from django.urls import reverse
from isbn_field import ISBNField
```

2024-12-03 16:03 UTC, Dmitry505 commented
@ayusavin 
С линтером не до разобрался, возникли не большие проблемы, в свободное время устраню. Остальное поправил.

2024-12-14 16:44 UTC, Dmitry505 commented
всё исправил, установил ruff

2025-06-02 10:17 UTC, merged